mLRS/Common/common.h, mLRS/CommonRx/mavlink_interface.h, mLRS/CommonRx/mlrs-rx.cpp
Hi olliw, with this additional commit, we will have a big different in downlink rate and packet lost. I got working on 57600 baud, just have packet lost when first connect to mission planner as FC send all parameter to mission planner. After all parameter had downloaded, I didn't have packet lost anymore. For this radio send status working we need a large buffer size on serial rx 8k working for me now
=> Add send mavlink radio status on rx side 

mLRS/CommonRx/clock.h
The cause of the large bursts of lost frames on the R9 Tx side turns out to be a problem on the Rx side.  But it's not a difference with the radio chip.  It's a difference with the STM32 controller used.  The code in clock.h assumed that TIM2 has a 16 bit wide counter, but on the STM32L4, TIM2 is 32 bits wide.  So, when Reset() is called, after CNT is larger than 2^16, the timer never fires and the receiver looses sync when the next frame is lost.
Note, I was unable to test this code on other receivers so this still needs testing.  I'm guessing that passing 0xFFFFFFFF in tim_init_up is ok even for 16 bit timers and that it will be truncated, but I haven't actually checked to be sure..  This is probably also not the only way to fix this bug.
I still see many more lost frames on the Tx side …
=> Allow for 32 bit TIM2

mLRS/CommonRx/mavlink_interface_rx.h
I discovered some problems when testing with Mavproxy and Mission Planner.
Without these changes, Mavproxy gets stuck trying to download parameters via ftp.
Use strncmp to allow for options at the end of the URL string.  Both Mission planner and Mavproxy request "@PARAM/param.pck?-withdefaults=1"
Mavproxy uses target component of 0 (all components).
Need to recalculate CRC or autopilot will just discard the message.
This has been tested with both Ardupilot and PX4 and Mavproxy, Mission Planner, and QGroundControl.
=> Fix ftp message rewriting

mLRS/Common/hal/rx-hal-wioe5-grove-wle5jc.h
Hi Olli, 
Here is the bug fix for the Grove E5 module as receiver. This should fix issue #42. 
The Serial port has pointing to the wrong UART.
PS: I am the only one experimenting with this?
=> bug fix: E5Grove, swap UART

mLRS/Common/common_conf.h, mLRS/Common/setup.h
Added 'FHSS_NUM_BAND_915_MHZ_FCC_19HZ_MODE' definition and switch statement to handle new definition.  No changes to the number of hop channels.
Built successfully for Wio E5.
=> 915 FCC FHSS definition update

mLRS/Common/hal/rx-hal-wioe5-mini-wle5jc.h
Hi Olli, 
I fell in love with your _new_ idea of the LED assembly for the tx-E5-mini. 
Mainly for debugging purposes I have to flash a "tx-E5-mini" with rx-firmware. The presence of a green LED or a real bind-button can help a lot (The rx-Gove-E5 is very limited). 
To be consistent (and interchangeable for debugging) I want to do the same trick here. 
Hopefully this don't break other existing assemblies. 
Let me know what you think.
Regards, Sascha
=> rx-E5-mini LED swap similar to tx-E5-mini

esp/mlrs-wifi-bridge/mlrs-wifi-bridge.ino
Add a define for WiFi channel, set to 13 which should overlap least with mLRS freq list and home WiFi.
Tested on my ESP32.
=> WiFi Channel Parameter

mLRS/Common/setup_list.h, mLRS/CommonRx/mavlink_interface_rx.h
This is mostly adopted from Olli's latest code in handle_txbuf_ardupilot() with some changes intended to improve response time.
Also change setup string from brad to other
In my testing, this seems to work at least as well for simple cases as the more complex code it replaces for both Ardupilot and PX4 and I think it should also adapt faster to extra traffic routed from cameras, gimbals, etc.
=> Rewrite handle_txbuf_px4()

esp/mlrs-wifi-bridge/mlrs-wifi-bridge.ino
With QGround control, on both Linux and Android, I got lots of lost MAVLink messages without this change.  When I checked, I saw that most UDP packets contained only a few bytes (1-3) of payload.  I don't know which end the messages were being lost on.
The intent of this change is to wait for more bytes to be received on the serial link before sending a UDP packet, but still constrain the latency to a reasonable 5ms.
=> Don't send so many very short UDP messages to avoid message loss

mLRS/Common/common_types.cpp, mLRS/CommonTx/crsf_interface_tx.h
EdgeTx handles this fine and shows negative RSSI - same values the driver provides.
Close to plane (-22 dB):
Further from plane (-38 dB):
=> Remove CRSF RSSI Inversion

mLRS/CommonTx/jr_pin5_interface.h
New define is 'JRPIN5_RX_TX_INVERT_SWAP_INTERNAL'
Added to the Hal after '#define JRPIN5_RX_TX_INVERT_INTERNAL'
Tested and working on E77 using 'S' pin for JR pin 5.
=> JR5 pin swap (mostly for E77 easysolder)

mLRS/rx-FRM303-f070cb/.project
fixes rx-FRM303 project folders location for Common, CommonRX and modules for relative paths.
=> fix: rx-FRM303 project folder location

mLRS/Common/hal/tx-hal-FRM303-f070cb.h
Fixes building for FRM303 transmitter with OLED, when OLED is mounted in normal direction.
=> fix(build): tx FRM303 OLED, normal orientation

mLRS/Common/hal/rx-hal-R9M-868-f103c8.h, mLRS/Common/hal/tx-hal-R9M-868-f103c8.h, mLRS/rx-R9M-f103c8/Core/Src/main.cpp, mLRS/rx-R9M-f103c8/STM32F103C8TX_FLASH.ld, mLRS/rx-R9MM-f103rb/Core/Src/main.cpp, mLRS/rx-R9MM-f103rb/STM32F103RBHX_FLASH.ld, mLRS/rx-R9MX-l433cb/Core/Src/main.cpp, mLRS/rx-R9MX-l433cb/STM32L433CBYX_FLASH.ld, mLRS/tx-R9M-f103c8/Core/Src/main.cpp, mLRS/tx-R9M-f103c8/STM32F103C8TX_FLASH.ld, mLRS/tx-R9MX-l433cb/Core/Src/main.cpp, mLRS/tx-R9MX-l433cb/STM32L433CBUX_FLASH.ld, tools/run_make_firmwares3.py
Olli,  Please review this and let me know what you think of the approach I have taken here to build a second version of the R9M firmware with the proper flash address and small code changes to work with the ExpressLRS bootloader.  This produces a .elrs file which can be flashed using OpenTX or ExperssTX without needing to erase the stock Frsky bootloader or solder wires for ST-Link.
I'm still working on testing this (a previous hand-built version worked well) and I haven't even started on user documentation, but I wanted to get your feedback before I continue this work.
Elsewhere you mentioned needing to move the isr table, but this is already taken care of by the ELRS bootloader since it sets the proper VTOR value to point to our isr table before jumping to our start address (which is …
=> Preliminary, not fully tested approach to building images for ExpressLRS bootloader

esp/mlrs-wifi-bridge/mlrs-wifi-bridge-boards.h, esp/mlrs-wifi-bridge/mlrs-wifi-bridge.ino
Usage: connect M5Stack ATOM Lite to mLRS via HY2.0-4P connectors G32 (RX of mlrs-wifi-bridge) and G26 (TX of mlrs-wifi-bridge).
The RGB LED of ATOM Lite will be used for signalling - blinking red while waiting for connection and blinking green for connected state.
=> feat: adds support for M5Stack ATOM Lite

esp/mlrs-wifi-bridge/mlrs-wifi-bridge-boards.h, esp/mlrs-wifi-bridge/mlrs-wifi-bridge.ino
Added std. "ESP32 Dev Module" (e.g. NodeMCU ESP32-WROOM-32) as a new option. Including also an inverted serial version for usage e.g. with FrSky R9M.
According to Discord user hooman, this code works with his R9M and NodeMCU ESP32-WROOM-32.
Update: tested myself with ESP32-DevKitC V4 with ESP32-WROOM-32D as well.
=> Added std. "ESP32 Dev Module"

mLRS/modules/stm32-usb-device/usbd_conf.c, mLRS/modules/stm32-usb-device/usbd_conf.h, tools/run_copy_st_drivers.py, tools/run_make_firmwares3.py
as discussed on the dirscord the first PR for supporting VCP on G4 MCUs. you @olliw42 already mentioned there isn't (a currently known) better way to define the includes for the G4 series in `mLRS/modules/stm32-usb-device/usbd_conf.h`.
Edits/Reviews/Suggestions to this PRs are as always welcome.
=> feat: added support for VCP on G4

README.md
Believe downlink speed should be 9111 Bytes / sec:
(1000/9) * 82 = 9111.111
Uplink is calculated correctly:
(1000/9) * 64 = 7111.111
=> flrc downlink fix

mLRS/modules/stm32-usb-device/usbd_cdc_if.c
implemented UsbClockSelection for the STM32G431xx. My hardware is running in this configuration since last week.
https://github.com/Gurkengewuerz/mLRS-custom-builds/blob/main/customTargets/mc8051-diy-g431cb/Core/Src/main.cpp#L170-L176
Tested on STM32G431CB
=> feat: added UsbClockSelection for STM32G431xx

mLRS/Common/sx-drivers/sx127x_driver.h
Related to: https://github.com/olliw42/mLRS/issues/139 Tested on R9 MX, Lua now reports expected value.
Previously, one would get a 'free' 4 dBm on power levels < 15 dBm.
=> SX127x_power_fix

platformio.ini
@tmcadam @jlpoltrack 
for one (or both) of you to review and if good to merge :)
title says it
procedural notes (just to bring Tom in the loop):
- I think any PR related to esp could start with "esp, " in the title :)
- since it's esp stuff one of you must approve. We started the habit to use the short lgtm to indicate approval (or one of you just merges, which is implict approval LOL)
- you will note that "merging" actually means "squash and merge". For explanation: I had set up the repo this way, since squash collapses all commits into one, otherwise we would have a pretty bloated commit history and it would be hard to follow the changes
- upon "squash and merge" you'll get a change to change the commit title. I'd like to pay a bit attention to it. Especially - following habits of …
=> esp, platformio.ini prepare for tx

mLRS/Common/hal/esp-timer.h, mLRS/Common/hal/esp/rx-hal-dev-sx1278-esp8266.h, mLRS/Common/hal/esp/rx-hal-generic-2400-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-2400-pa-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-900-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-900-pa-esp8285.h
moves SYSTICK defines from device hal files to hal.h and timer.h
this follows the cleanify for the stm32 code
it's nfc
tested to compile for all esp targets, and work for speedybee
=> esp, rx,tx, hal cleanify, sync with stm, move SYSTICK define, nfc

mLRS/Common/sx-drivers/sx127x_driver.h
New define 'SX_USE_RFO' for SX127x hardware that uses the RFO pin instead of the PA_BOOST pin for output.  Tested by Joost on BR3.
=> rx, tx SX127x, rfo define

mLRS/Common/esp-lib/esp-delay.h, mLRS/Common/esp-lib/esp-eeprom.h, mLRS/Common/esp-lib/esp-mcu.h, mLRS/Common/esp-lib/esp-peripherals.h, mLRS/Common/esp-lib/esp-spi.h, mLRS/Common/esp-lib/esp-uartb.h, mLRS/Common/hal/esp-glue.h, mLRS/Common/hal/esp-rxclock.h, mLRS/Common/hal/esp/rx-hal-dev-900-esp32.h, mLRS/Common/hal/esp/rx-hal-dev-sx1278-esp8266.h, mLRS/Common/hal/esp/rx-hal-generic-2400-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-2400-pa-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-2400-td-pa-esp32.h, mLRS/Common/hal/esp/rx-hal-generic-900-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-900-pa-esp8285.h, mLRS/Common/hal/hal.h, mLRS/Common/sx-drivers/sx128x_driver.h, mLRS/CommonRx/mlrs-rx.cpp, platformio.ini
this does some tidies and cleanups
they all should be nfc
the large majority are really just formatting, blanks, etc.
the major changes were done to the use of DIVERSITY_SINGLE_SPI. It seems to me the driver had been essentially identical and needed only minor change, so I put it into one driver.
tested to not have changed the working on a RP4TD
=> dev-esp-rx-td, some tidies to branch dev-esp-rx-td, nfc

mLRS/Common/esp-lib/esp-peripherals.h, mLRS/Common/esp-lib/esp-spi.h, mLRS/Common/esp-lib/esp-uartb.h, mLRS/Common/hal/device_conf.h, mLRS/Common/hal/esp-glue.h, mLRS/Common/hal/esp/rx-hal-dev-900-esp32.h, mLRS/Common/hal/esp/rx-hal-dev-sx1278-esp8266.h, mLRS/Common/hal/esp/rx-hal-generic-2400-td-pa-esp32.h, mLRS/Common/hal/hal.h, mLRS/Common/leds.h, platformio.ini
title says it, more tidies from my side
- the large majority are nfc, and really just formatting
- in esp-uartb.h I have replaced some inline by static inline (Note: inline is useless, it needs to be static inline)
- in platformio there was a bug, in there a esp826xx target was taking esp build flags
- added RM RP4TD as selected target device
- changed things in the dev targets, hope I got that correct
=> dev-esp-rx-td, more tidies, mostly nfc

mLRS/Common/hal/esp-glue.h, mLRS/Common/hal/esp/rx-hal-dev-900-esp32.h, mLRS/Common/hal/esp/rx-hal-dev-sx1278-esp8266.h, mLRS/Common/hal/esp/rx-hal-generic-2400-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-2400-pa-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-2400-td-pa-esp32.h, mLRS/Common/hal/esp/rx-hal-generic-900-esp8285.h, mLRS/Common/hal/esp/rx-hal-generic-900-pa-esp8285.h, mLRS/Common/hal/glue.h, mLRS/CommonRx/mlrs-rx.cpp, mLRS/CommonTx/mlrs-tx.cpp, platformio.ini
title says it
also added a new target 2400-pa-dcdc, is consequence of me testing the betafpv nano 2.4G receiver ... appears to work equally well without and with DCDC, let's see. Thought better to have it for now.
We could do the same approach of a dcdc target for the betafpv-superd-2400, but can do this later too LOL
tested on betafpv nano 2.4G and nano 900 MHz
=> dev-esp-rx-td, hopefully last set of tidies II

mLRS/Common/hal/esp/rx-hal-radiomaster-br3-900-esp8285.h, mLRS/Common/sx-drivers/sx127x_driver.h
Account for reducing SX power to 11.4 dBm when using RFO output.
=> dev-esp-rfo, br3 proper

mLRS/Common/common_types.cpp, mLRS/Common/common_types.h, mLRS/CommonRx/out.cpp
Rename the functions which calculate RSSI and LQ for use on an RC channel to be consistent with their purpose and use.  Adjust range of LQ calculation to occupy the full (100%) RC range for more accurate LQ readings without adjusting the range in Ardupilot parameters.
Now, with the default Ardupilot range, the correct full LQ range will now be reported when using RC override.  But the range is still not quite correct when using sbus since Ardupilot and PX4 do not agree with mLRS on the exact range of sbus channel values.  But, at least we get closer with a maximum of 99% reported instead of 94%.  Betaflight and INAV do agree mLRS with respect to sbus channel range.
=> Improve LQ over rc channel function

mLRS/Common/common_conf.h
AETR is default order for OpenTx, EdgeTx and AP - so I think this would mean one less setting for folks to change.
=> tx aetr default

mLRS/Common/esp-lib/esp-uart-template.h, mLRS/Common/esp-lib/esp-uart.h, mLRS/Common/esp-lib/esp-uartb.h, mLRS/Common/esp-lib/esp-uartc.h, mLRS/Common/esp-lib/esp-uartd.h, mLRS/Common/esp-lib/esp-uartf.h, mLRS/Common/hal/esp/rx-hal-radiomaster-rp4td-2400-esp32.h
@tmcadam or @jlpoltrack 
title says it
largely just nfc changes
Two changes relevant to EPS32:
- check of txbuf size, this is what is concluded in the tx module attempt branches
- no tx flush
These were concluded in the tx branches using the esp-idf. Since it's used lowlevel also here I think this shoulöd also apply here,
=> esp, lib, tdiy uart lib

mLRS/Common/hal/esp/rx-hal-generic-900-td-pa-esp32.h
title says it
- swaps sx and sx2, so that antenna1 is on left ufl, like for the iflight2400 td 250mW
- lowers the power. gives proper values for 100 mW and 250 mW. For 500 mW setting it's lower by 50 mW, but it was low anyway. It appears the PA has reached already nonlinear region, and I don't think one should go too high into it
bench tested on iflight 900 500 mW receiver
I'm not sure we should keep the iflight900 in the docu list. Mine does not appear to work reliable. I cannot change settings without the thing going into continous reset upon next power up. No idea what this is. Also, the transmission appears to be flimsy, when I move or touch it the radio sometimes loses like 1/2 sec worth of packets. Could be the antenna or the connectors, or the hardware itself, don't know, but from …
=> esp, rx, iflight900, swap sx, adjust power

mLRS/Common/setup.h
Temporary solution to prevent getting stuck if one selects Antenna 2 on single SPI diversity hardware.
=> common, setup disable antenna 2 on single SPI

mLRS/Common/sx-drivers/sx126x_driver.h
Binding was broken when using SX126x and starting in FSK mode, this fixes.  Tested on Matek hardware.
Similar commit that was needed for FLRC: https://github.com/olliw42/mLRS/commit/4dce99c798c9846bd8d910e7ecf274dffc8840a6
=> common, sx126x fsk bind fix

mLRS/Common/hal/esp/rx-hal-generic-2400-esp8285.h
Tested on RP2 receiver.  Previously, there was no LED when connected.
=> esp generic 2400 led logic swap

mLRS/CommonRx/mavlink_interface_rx.h, run_setup.py
This PR updates `run_setup.py` to make it run more consistently regardless of platform or system setup:
- checks for python or python3
- changes run_setup.py sub-commands to use python (or python3) explicitly
- updates the script to use subprocess module instead of os.system
- adds a --verbose option to run with or without output
=> Check python version in run_setup.py + verbose option

mLRS/Common/hal/matek/rx-hal-matek-mr900-22-wle5cc.h
Enables the DC-DC converter for the Matek mR900-22.  Tested and works fine - should save about 10mA based on previous tests with Wio E5 Mini.
=> matek, mr900-22 dc-dc

mLRS/Common/hal/stm32/rx-hal-WioE5-Mini-wle5jc.h
Enables one to enter the system bootloader on E5 Mini receiver using the button, mostly for convenience.  
Process: - hold down button, then hit reset button.
=> Wioe5 rx system boot

lua/mLRS.lua
Adds more lines to the settings pages for Jumper T15 (and other 320 res radios).
Before: 
After:
=> lua, 320 res settings support

mLRS/Common/hal/hal-power-pa.h, mLRS/Common/sx-drivers/sx126x_driver.h
- Enables 50 mW, 100 mW power levels on mR900-30 gear
- Adds 3 dBm power level to bare SX127x to allow for symmetric power output with minimum R9M power level
- Comment tidy
=> mR900 Power Tweaks

run_setup.py
Was needed when using an install of Python which used 'python3' for the binary.
=> python3 fix

lua/mLRS-bw.lua
When shortening variable names to save memory, I missed a couple which affected only editing the bind phrase
=> Fix crash when editing bind phrase

mLRS/Common/hal/stm32/rx-hal-diy-e28dual-board02-f103cb.h, mLRS/Common/hal/stm32/tx-hal-diy-e28dual-board02-f103cb.h
Updates for the F1 E28 Dual board:
- Increase SPI speed to 18 MHz, helps with jitter
- Enable DC-DC converter on E28, saves about 20 mA (2 x 10 mA)
Have been running this configuration myself for long time.
=> DIY F1 E28 DC-DC Updates

mLRS/Common/fan.h, mLRS/CommonRx/mlrs-rx.cpp, mLRS/CommonTx/mlrs-tx.cpp
When using switchable power + fan on/off, fan is only configured during boot - this updates the fan to use the current power level in the main loop.
When using 500 mW + switchable power:
Before - fan on all the time
After - fan on only at 500 mW
=> rx, tx dynamic fan

mLRS/Common/hal/esp-timer.h, mLRS/Common/hal/timer.h, mLRS/CommonRx/mlrs-rx.cpp, mLRS/CommonTx/esp.h, mLRS/CommonTx/hc04.h, mLRS/CommonTx/mlrs-tx.cpp
Since the "--" operator is not generally atomic in RISC architectures and, I believe, specifically not on STM32 or ESP32 where the decrement is implemented as load, modify, store, the change from clearing doSysTask to decrementing it introduced a race.
I am not aware that this race has ever caused an observed problem as it should be fairly rare, but, consider what would happen.
In the case where the ISR executes between the load and store; the increment in HAL_IncTick() is effectively lost which can make the Tx transmit 1 ms late which could cause the problem on the Rx which we are now all too familiar with.
I believe the method implemented here is the most efficient way to avoid this race.
=> Fix race when tasks take longer than doSysTask tick

mLRS/Common/hal/hal-power-pa.h, mLRS/Common/sx-drivers/sx128x_driver.h
- Adds power table for 65383
- 50 mW instead of min
- Tested on Matek mr24-30 Tx
=> Mr24 power tweaks

mLRS/Common/common.h, mLRS/Common/time_stats.h, mLRS/CommonRx/mlrs-rx.cpp, mLRS/CommonTx/mlrs-tx.cpp
for measuring min/max/ave time spent in one or more code paths. This may be useful for debugging and optimizing time critical operations.
=> Add simple time statistics functions

mLRS/Common/hal/esp/tx-hal-jumper-int-2400-esp32.h, mLRS/Common/hal/esp/tx-hal-radiomaster-int-2400-esp32.h, mLRS/CommonTx/esp.h
after configuring passthrough using EdgeTx CLI
Define esp_boot0() for internal Tx modules
This has been tested with 2.4 GHz internal Tx modules on Radiomaster Pocket and Jumper T15 using ETXinitPassthrough.py which will be coming in a separate PR.
It also works with the ELRS version of esptool.
=> Setup to flash backpack via standard tools

mLRS/Common/esp-lib/esp-uart-template.h, mLRS/Common/esp-lib/esp-uart.h, mLRS/Common/esp-lib/esp-uartb.h, mLRS/Common/esp-lib/esp-uartc.h, mLRS/Common/esp-lib/esp-uartd.h, mLRS/Common/esp-lib/esp-uarte.h, mLRS/Common/esp-lib/esp-uartf.h, mLRS/Common/hal/esp/tx-hal-jumper-int-2400-esp32.h, mLRS/Common/hal/esp/tx-hal-jumper-int-900-esp32.h, mLRS/Common/hal/esp/tx-hal-radiomaster-bandit-series-900-esp32.h, mLRS/Common/hal/esp/tx-hal-radiomaster-int-2400-esp32.h, mLRS/Common/hal/hal.h, mLRS/CommonTx/crsf_interface_tx.h, mLRS/CommonTx/jr_pin5_interface.h, mLRS/CommonTx/jr_pin5_interface_esp.h, mLRS/CommonTx/jr_pin5_interface_no_tc.h, mLRS/CommonTx/mbridge_interface.h, mLRS/CommonTx/mlrs-tx.cpp
Half duplex JRpin5 for esp32
Leverage esp32 serial MODE_RS485_HALF_DUPLEX and GPIO_DRIVE_CAP_0 to work around the missing TC interrupt for JRpin5.
=> Esp jrpin5 external

mLRS/Common/setup.h
FSK on diversity hardware (DBR4, XR4) showed link drops with Matek mR900 Tx, so restricting to 19 and 31 Hz.
=> LR11xx No FSK

lua/mLRS-bw.lua
This change allows internal modules to be used on the RM Boxer, or other B&W radios that have ELRS internal modules (?). It replicates the color lua functionality in this regard.
=> lua, enable internal modules on bw radios

platformio.ini
LR1121 TD is an ESP32 _not_ ESP32C3
=> fix lr1121 td extend

mLRS/Common/hal/esp-rxclock.h, mLRS/CommonRx/mlrs-rx.cpp
Interrupts on ESP32 take something like 1-2 us, so a 10 us interrupt (100 KHz) means something like 100-200ms per second was being used to service this interrupt.
Previously FSK on DBR4 / XR4 would show bad link drops when running 115200 baud.  Now the LQ is rock solid at 100% when running FSK with 230400 baud.  ESP32C3 can use the same code even though it is single core.
Tested on:
- RadioMaster XR4
- RadioMaster XR1
- BetaFPV SuperD
=> ESP32 Rx Clock on Core 0

mLRS/CommonTx/crsf_interface_tx.h
- Adds addresses to device info
<del> - Removed version from device_name, otherwise it would be too long.  Example: 'mLRS ' + 20 char + ' v1.3.05' = 5 + 20 + 8 = 33 and can only be 32.
- Note that we don't seem to enforce 20 char limit on the Tx side, e.g. BetaFPV Micro1W 2.4G is 21... </del> 
Somehow thought 32 char was the limit, this is not the case...
Tested working with BetaFPV Micro 1W on EdgeTx 2.11 RC2
=> Add addresses to CRSF device info

mLRS/Common/protocols/crsf_protocol.h, mLRS/CommonTx/crsf_interface_tx.h, mLRS/CommonTx/mlrs-tx.cpp
attempt to account for https://github.com/olliw42/mLRS/issues/297
not tested, just did some code
@jlpoltrack maybe you find a chance to test this out :)
=> tx, crsf, send device info upon ping device

mLRS/CommonTx/crsf_interface_tx.h
Since the radio asked for the device information, should probably set the destination as the radio.
Tested on BetaFPV and E28 Dual with EdgeTx 2.11, no issues.
=> Device Info Destination Update

mLRS/CommonTx/jr_pin5_interface_esp.h
Updates to the ISR and the pin5_tx_enable function address the ghost byte caused by switching the pin.  This means that the callback is only triggered at the end of a message received from the radio.  All switching is done by the ISR as opposed to the mix that was there before.
=> Esp half duplex improvements

mLRS/CommonTx/jr_pin5_interface_esp.h
- Enable internal (50k) pull-down permanently
- Move RX FIFO reset to after the GPIO commands
- Set inverted logic when doing the RX detach in Tx enable (on my branch with faster flash I noticed that some single byte callbacks were still being triggered, this resolved).
- Fix initialization, Lua wouldn't work after changing parameters
=> Esp Tx, more half duplex

platformio.ini
Title - had no impact as build flags are the same across both.
=> XR1 is ESP32 C3

mLRS/CommonTx/esp.h
After changing the bridge to 9600 or 19200 baud, we couldn't switch back to higher speeds.
Tested with Radiomaster Pocket internal ELRS module.
=> Fix bridge speed detection.

tools/run_make_firmwares.py
KISS way to override toolchain dirs for your needs.
```
export MLRS_ST_DIR="/Users/username/Applications/STM32CubeIDE.app"
export MLRS_GNU_DIR="Contents/Eclipse/plugins/com.st.stm32cube.ide.mcu.externaltools.gnu-tools-for-stm32.12.3.rel1.macos64_1.0.100.202403111906/"
python tools/run_make_firmwares.py
```
=> Override stm32cube IDE dirs via OS env
