mLRS/Common/sx-drivers/sx126x.cpp
mLRS/Common/sx-drivers/sx126x.h
mLRS/Common/sx-drivers/sx126x_driver.h
mLRS/CommonRx/mlrs-rx.cpp
mLRS/CommonTx/mlrs-tx.cpp

Sx1262 setTxParameter (power) use actual value in dbm. with set PA config to max 22dbm we have range -9 to 22 dbm
and value we pass on setTxParameter is actual value (-9 ... 22)

introduce GetAndClearIrq and clear event on sx1262, also fix the calc_sx_power

---

mLRS/Common/sx-drivers/sx126x_driver.h

SxDriverDummy class re definition, delete on sx126x_driver.h

Moved on to sx12xx_driver.h

---

mLRS/CommonTx/disp.h
mLRS/CommonTx/gdisp.c
mLRS/CommonTx/gdisp.h

issues #16 https://github.com/olliw42/mLRS/issues/16

issues #16

---

docs/FRSKY_R9.md

Hi Olli, 
I try to improve the documentation.

docs: Frsky R9 docu

---

docs/FRSKY_R9.md

Hi @olliw42 
Here the promised docs for tx-R9MX. It's for advanced users only.

tx-R9MX docu

---

run_setup.py

This should fix the trouble some people have with run_setup.py on Linux
I have not checked that this still works on Windows, but I think it should.

Don't assume the current directory is in the execution path

---

mLRS/CommonRx/mavlink_interface_rx.h

Fix off by one error;  No change should use txbuf=50

---

mLRS/Common/hal/rx-hal-R9M-868-f103c8.h
mLRS/Common/hal/rx-hal-diy-e28-g441kb.h
mLRS/Common/hal/rx-hal-diy-e28dual-board02-f103cb.h
mLRS/Common/hal/tx-hal-R9M-868-f103c8.h
mLRS/Common/hal/tx-hal-diy-e28-g431kb.h
mLRS/Common/hal/tx-hal-diy-e28dual-board02-f103cb.h
mLRS/Common/hal/tx-hal-diy-e28dual-module02-g491re.h

24 dBM instead of 23

---

mLRS/Common/setup.h

Fix path directory delimiter for Linux

---

mLRS/Common/sx-drivers/sx128x_driver.h

Needed with: https://github.com/olliw42/sx12xx-lib/pull/4

Update SX128x to handle RSSI 16 Bit

---

mLRS/Common/fhss.cpp
mLRS/Common/setup_list.h

- Small channel list fix
- Spelling in setup_list

IN 866 Fixes

---

lua/mLRS-bw.lua

add lua for small B/W screen radio. Only save five fixed parameters infomation to avoid out of memory. They are BindPhrase/Mode/TxPwr/RxPwr/RxOutMode

add lua supports B/W screen,5 fixed parameters

---

mLRS/Common/bind.h
mLRS/Common/sx-drivers/sx12xx_driver.h

Untested at the moment, my Rx hardware don't have bind buttons.

FLRC Bind updates

---

tools/run_make_firmwares3.py

like #124 also discussed on #hardware channel in discord. this is needed to support the g431**cb** series different with more I/O and 48 pins from the already supported g431**kb** series.
here also applies reviews/edits/suggestions are welcome.

feat: added g431cb support for firmware3 build script

---

mLRS/CommonTx/crsf_interface_tx.h

Have been doing some testing with 100, 111 and 125 Hz modes for FLRC and this change was needed for all of them.

high refresh crsf tweak

---

mLRS/Common/hal/tx-hal-diy-wioe5-e22-wle5jc.h

Copied from Rx Hal, does compile with diversity enabled but untested on hardware (don't have)

e5, SPI2 define

---

mLRS/CREATE_TARGET_INSTRUCTIONS.md

Hey guys, just some minor fix (took me a couple of seconds to parse the typo myself...)

Minor fix in CREATE_TARGET_INSTRUCTIONS.md

---

mLRS/Common/common_conf.h
mLRS/Common/common_types.cpp
mLRS/Common/setup.h
mLRS/Common/setup_list.h
mLRS/Common/setup_types.h
mLRS/Common/sx-drivers/sx126x_driver.h
mLRS/CommonRx/mavlink_interface_rx.h

Tested and worked on 2x E5 Mini.
- New FSK Mode
- SX126x driver uses GFSK references to align with datasheet

Sx126x fsk

---

mLRS/CommonRx/mavlink_interface_rx.h

USE_FEATURE_MAVLINKX had a couple of problems with respect to txbuf calculations which badly broke flow control.
1) The calculation of buffered received serial data in serial_in_available() needs to include the data which is in the process of being parsed as well as the data which has already been parsed but not yet sent over the radio link.
2) We should not parse and transfer to fifo_link_out more than one message in the while loop since we only checked that there is space for one message.  We also shouldn't spend too much time here without doing flow control.

Fix flow control broken by USE_FEATURE_MAVLINKX

---

mLRS/CommonTx/cli.h

cli freq typo

---

mLRS/CommonTx/cli.h

Cli typo oops

---

mLRS/Common/fail.h
mLRS/Common/leds.h

single led update

---

mLRS/Common/esp-lib/esp-delay.h
mLRS/Common/esp-lib/esp-eeprom.h
mLRS/Common/esp-lib/esp-mcu.h
mLRS/Common/esp-lib/esp-peripherals.h
mLRS/Common/esp-lib/esp-spi.h
mLRS/Common/esp-lib/esp-uartb.h
mLRS/Common/hal/esp-rxclock.h
platformio.ini

brings in to main some things from the dev-esp-rx-td branch, which were considered good there
mostly tidies, hence nfc
but also few nominally non-nfc things

esp. sync with other branches, tidies

---

mLRS/Common/hal/glue.h

stm, fix GCC protection

---

esp/mlrs-wireless-bridge-esp8266/mlrs-wireless-bridge-esp8266.ino
esp/mlrs-wireless-bridge/mlrs-wireless-bridge-boards.h
esp/mlrs-wireless-bridge/mlrs-wireless-bridge.ino

As ESP8266 cannot do Bluetooth, this edition supports WiFi only.
Tested with ESP-01S, but needs more testing.

Added mLRS-Wireless-Bridge for ESP8266

---

platformio.ini

esp, pio iflight fix

---

mLRS/Common/hal/esp/rx-hal-iflight-elrs-td-2400-esp32.h

title says it
bench tested on an iflught 2400 250mW

esp, rx, iflight2400 250mW, adjust power levels

---

mLRS/Common/common_conf.h

common, tx radio status enabled by default

---

tools/flash_rx_via_ap_passthru3.py

Allow for posix systems to install their own local copy of STM32_Cube_Prog
Don't time out passthrough to allow easier manual use of flash tool 
Fix hard coded serial in call to ardupilot_read_baud

A small bug fix and improve use on Linux

---

mLRS/Common/hal/esp/esp-device_conf.h
mLRS/Common/hal/esp/esp-hal.h
mLRS/Common/hal/esp/tx-hal-radiomaster-bandit-micro-900-esp32.h
mLRS/Common/hal/esp/tx-hal-radiomaster-bandit-series-900-esp32.h
platformio.ini

Attempt to address a few things when using Bandit Micro FW on Big Bandit:
- Flip the Display
- Enable two LEDs
First attempt was to use a separate HAL like RP4TD but redefine of LED functions was ugly.  Figured it may make more sense to keep all in one HAL file.
@tmcadam FYI

Big Bandit Tx

---

esp/mlrs-wireless-bridge-esp8266/mlrs-wireless-bridge-esp8266.ino

esp8266 assigns ip+99 instead of ip+1 for first DHCP client

Don't use broadcast to avoid lost messages

---

mLRS/Common/sx-drivers/lr11xx_driver.h

Updates to prepare for Nomad hardware:
- New define which allows the use of the low power amplifier for 900 MHz
- Function for custom power calc

common, lr driver power update

---

mLRS/Common/sx-drivers/lr11xx_driver.h
mLRS/Common/sx-drivers/sx126x_driver.h
mLRS/Common/sx-drivers/sx128x_driver.h
mLRS/Common/sx-drivers/sx12xx_driver.h

Move RF modes to sx12xx_driver

---

mLRS/Common/hal/esp/tx-hal-radiomaster-bandit-series-900-esp32.h

Also Somewhat allign UARTs setup with JLP's nomad PR

Bandit: Disable debug port and restore com/serial

---

mLRS/CommonTx/cli.h

Split help and pl output accross multiple calls to cli.do()

---

mLRS/Common/hal/esp/tx-hal-betafpv-micro-1w-2400-esp32.h
mLRS/Common/hal/hal.h
platformio.ini

- Remove mention of sik
- General cleanup

Beta FPV Hal Update

---

ardupilot_tools/mlrs_mavlink_link_stats.lua

Adds a somehwat tidied version of twistedwings Lua script for ArduPilot, to log the link statistics data.
I could not give it any testing myself. So, needs to be tested if my changes have screwed it up :)
@jlpoltrack

Add ArduPilot tool, link statistics Lua script (thx to twistedwings)

---

mLRS/Common/rf_power.h

To address the power bug described here: https://github.com/olliw42/mLRS/issues/288

rf power boot fix

---

mLRS/Common/esp-lib/esp-uart-template.h
mLRS/Common/esp-lib/esp-uart.h
mLRS/Common/esp-lib/esp-uartb.h
mLRS/Common/esp-lib/esp-uartc.h
mLRS/Common/esp-lib/esp-uartd.h
mLRS/Common/esp-lib/esp-uarte.h
mLRS/Common/esp-lib/esp-uartf.h
mLRS/Common/hal/esp/tx-hal-betafpv-micro-1w-2400-esp32.h
mLRS/Common/hal/esp/tx-hal-radiomaster-bandit-series-900-esp32.h

Bandit, In Functionality

---

mLRS/Common/esp-lib/esp-uart-template.h
mLRS/Common/esp-lib/esp-uart.h
mLRS/Common/esp-lib/esp-uartb.h
mLRS/Common/esp-lib/esp-uartc.h
mLRS/Common/esp-lib/esp-uartd.h
mLRS/Common/esp-lib/esp-uarte.h
mLRS/Common/esp-lib/esp-uartf.h
mLRS/CommonTx/jr_pin5_interface_esp.h

Add a getbuf function the ESP UART lib.

esp uart getbuf + jr pin read

---

mLRS/rx-E77-MBLKit-wle5cc/Core/Src/main.cpp
mLRS/rx-Wio-E5-Grove-wle5jc/Core/Src/main.cpp
mLRS/rx-Wio-E5-Mini-wle5jc/Core/Src/main.cpp
mLRS/rx-diy-WioE5-E22-dual-wle5jc/Core/Src/main.cpp
mLRS/rx-easysolder-E77-E22-dual-wle5cc/Core/Src/main.cpp
mLRS/rx-easysolder-E77-E28-dualband-wle5cc/Core/Src/main.cpp
mLRS/rx-matek-mr900-22-wle5cc/Core/Src/main.cpp
mLRS/tx-E77-MBLKit-wle5cc/Core/Src/main.cpp
mLRS/tx-Wio-E5-Mini-wle5jc/Core/Src/main.cpp
mLRS/tx-diy-WioE5-E22-dual-wle5jc/Core/Src/main.cpp
mLRS/tx-easysolder-E77-E22-dual-wle5cc/Core/Src/main.cpp
mLRS/tx-easysolder-E77-E28-dualband-wle5cc/Core/Src/main.cpp

title says it
only for WLE5 for now, as a first step
lightly tested for easysolder dualband as rx and tx, and WioE5 Mini board as tx

targets wle5xx, enable prefetch, I cache, disable D cache

---

mLRS/Common/hal/esp/esp-device_conf.h
mLRS/Common/hal/esp/esp-hal.h
mLRS/Common/hal/esp/tx-hal-radiomaster-ranger-2400-esp32.h
platformio.ini

Add support for "big" Radiomaster Ranger.
@jlpoltrack, I used your fan code.  Thanks!
Also, I guess I still don't have a firm grasp on adapting the info from ELRS targets.  based on their power_values, I calculated that POWER_GAIN_DBM should be 30, but that resulted in measured peak power of over twice what it was set too.  33 seems to work perfectly, but can someone explain why?

Radiomaster ranger

---

README.md

readme desktop app

---

esp/mlrs-wireless-bridge/mlrs-wireless-bridge.ino
mLRS/Common/setup.h

Third attempt
@olliw42 I've tried to stay as close as possible to what you had in your PR which you abandoned.  This means I have not attempted to improve UDPCL, even though I think at the very least, it should try to re-connect like UDP STA does when WiFi gets disconnected.  Hopefully you will decide to drop UDPCL someday so it won't matter.

UDP STA mode and broadcast UDP

---

mLRS/Common/bind.h

Just check for presence of SX127x, not dual?

bind, just sx127x
